version: '3.9'
services:
  permissionpanther:
    image: ghcr.io/thesaaszoo/permissionpanther:latest
    environment:
      - ADMIN_KEY=TEST_ADMIN_KEY # CHANGE ME!!!!!!!!!!!
      - CRDB_DSN=postgresql://root@crdb:26257/defaultdb?sslmode=disable
      - DEBUG=1
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - crdb
  crdb:
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    ports:
      - 26257:26257
