const fs = require('fs/promises')

async function main() {
  const original = await fs.readFile('schema.sql', { encoding: 'utf-8' })
  const lines = original.split('\n')
  const newLines = lines.map((line) => {
    if (line.startsWith("CREATE INDEX")) {
      // Skip
    } else if (line.includes("ON UPDATE NOW()")) {
      // Remove that
      return line.replace("ON UPDATE NOW()", "")
    } else if (line.includes("DESC")) {
      // Remove that
      return line.replace(/DESC/g, "")
    } else {
      return line
    }
  })
  const final = [
    "-------------------------------------------------------",
    "-- SQL generated by makeSqlcSchema.js - DO NOT EDIT. --",
    "-------------------------------------------------------"
  ].concat(newLines)
  await fs.writeFile("sqlcSchema.sql", final.join("\n"))
}

main()
