-------------------------------------------------------
-- SQL generated by makeSqlcSchema.js - DO NOT EDIT. --
-------------------------------------------------------
CREATE TABLE IF NOT EXISTS relations (
  object TEXT NOT NULL,
  entity TEXT NOT NULL,
  permission TEXT NOT NULL,
  ns TEXT,
  PRIMARY KEY (ns, entity, permission, object)
);


