-------------------------------------------------------
-- SQL generated by makeSqlcSchema.js - DO NOT EDIT. --
-------------------------------------------------------
CREATE TABLE IF NOT EXISTS relations (
  object TEXT NOT NULL,
  entity TEXT NOT NULL,
  permission TEXT NOT NULL,
  ns TEXT NOT NULL,
  PRIMARY KEY (ns, entity, permission, object)
);



CREATE TABLE IF NOT EXISTS keys (
  id TEXT NOT NULL,
  secret_hash TEXT NOT NULL,
  ns TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  max_recursions INT8 NOT NULL,
  PRIMARY KEY (id)
);


