-------------------------------------------------------
-- SQL generated by makeSqlcSchema.js - DO NOT EDIT. --
-------------------------------------------------------
CREATE TABLE IF NOT EXISTS relations (
  object TEXT NOT NULL,
  entity TEXT NOT NULL,
  permission TEXT NOT NULL,
  ns TEXT NOT NULL,
  PRIMARY KEY (ns, entity, permission, object)
);



CREATE TABLE IF NOT EXISTS keys (
  id TEXT NOT NULL,
  secret_hash TEXT NOT NULL,
  ns TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  max_recursions INT8 NOT NULL,
  PRIMARY KEY (id)
);



CREATE TABLE IF NOT EXISTS permission_groups (
  name TEXT NOT NULL,
  ns TEXT NOT NULL,
  perms TEXT[] NOT NULL,
  PRIMARY KEY (ns, name)
);

CREATE TABLE IF NOT EXISTS permission_group_membership (
  group_name TEXT NOT NULL,
  entity TEXT NOT NULL,
  ns TEXT NOT NULL,
  object TEXT NOT NULL, -- for faster permission change propagation
  PRIMARY KEY(ns, group_name, entity)
);

