# https://taskfile.dev

version: '3'

env:
  GOMAXPROCS: "1"

dotenv: ['.env']

tasks:
  default:
    cmds:
      - go run .
  sqlc:
    cmds:
      - node makeSqlcSchema.js
      - sqlc generate
  proto:
    cmds:
       - protoc --go_out=. --go_opt=paths=source_relative
        --go-grpc_out=. --go-grpc_opt=paths=source_relative
        -I=./ pb/*.proto
    silent: true
  js:
    cmds:
       - grpc_tools_node_protoc --js_out=import_style=commonjs,binary:./js/src
        --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts
        --grpc_out=grpc_js:./js/src
        --ts_out=./js/src
        pb/*.proto
    silent: true
