apiVersion: v1
kind: Service
metadata:
  name: permission-panther
  namespace: default
  labels:
    app: permission-panther
spec:
  selector:
    app: permission-panther
  type: ClusterIP
  ports:
  - name: permission-panther
    protocol: TCP
    port: 80
    targetPort: 8080
