// Code generated by sqlc. DO NOT EDIT.

package query

import ()

type Key struct {
	ID         string
	SecretHash string
	Ns         string
}

type Relation struct {
	Object     string
	Entity     string
	Permission string
	Ns         string
}
