// Code generated by sqlc. DO NOT EDIT.

package query

import (
	"time"
)

type Key struct {
	ID         string
	SecretHash string
	Ns         string
	CreatedAt  time.Time
}

type Relation struct {
	Object     string
	Entity     string
	Permission string
	Ns         string
}
