name: Deploy Docs Website
on:
  push:
    branches:
      - main
      - add-docs-website
jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docusaurus
        run: ls && cd docs_web && npm run build
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
